In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_excel("../data/raw/zomato_data.xlsx")

df.head()

,Order ID,Order Amount (INR),Delivery Time (mins),Order Date,Rating,Number of Items,Delivery Distance (km),Delivery Agent ID,Order Status,Payment Method,...,average_cost_for_two,price_range,highlights,aggregate_rating,votes,photo_count,opentable_support,delivery,state,area
0,1,1930,32,2023-04-30,4.6,9,9.200017,995,Cancelled,Debit Card,...,200,1,"['Credit Card', 'Delivery', 'Takeaway Availabl...",0.0,3,0,0.0,0,Kerala,38863
1,2,371,84,2023-01-06,2.7,1,8.175074,941,Cancelled,UPI,...,1000,3,"['Cash', 'Takeaway Available', 'Breakfast', 'N...",3.6,32,30,0.0,1,Uttar Pradesh,240928
2,3,1389,82,2024-02-18,3.9,5,13.280443,469,Delivered,Debit Card,...,1300,3,"['Cash', 'Debit Card', 'Credit Card', 'Indoor ...",4.4,174,429,0.0,0,Tamil Nadu,130058
3,4,329,50,2023-07-06,1.9,1,11.892893,329,In-Transit,UPI,...,400,1,"['Delivery', 'No Alcohol Available', 'Lunch', ...",3.5,33,48,0.0,0,Delhi,1484
4,5,400,19,2024-06-21,3.4,4,2.570476,172,Cancelled,Credit Card,...,4000,4,"['Cash', 'Dinner', 'Credit Card', 'Lunch', 'Ou...",4.1,112,134,0.0,0,Rajasthan,342239

In [7]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 12079
Columns: 33

In [8]:
df.columns.tolist()

['Order ID',
 'Order Amount (INR)',
 'Delivery Time (mins)',
 'Order Date',
 'Rating',
 'Number of Items',
 'Delivery Distance (km)',
 'Delivery Agent ID',
 'Order Status',
 'Payment Method',
 'Tip Amount (INR)',
 'Promo Code Applied',
 'Has Free Delivery',
 'res_id',
 'name',
 'type',
 'address',
 'city',
 'locality',
 'latitude',
 'longitude',
 'cuisines',
 'timings',
 'average_cost_for_two',
 'price_range',
 'highlights',
 'aggregate_rating',
 'votes',
 'photo_count',
 'opentable_support',
 'delivery',
 'state',
 'area']

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12079 entries, 0 to 12078
Data columns (total 33 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order ID                12079 non-null  int64
 1   Order Amount (INR)      12079 non-null  int64
 2   Delivery Time (mins)    12079 non-null  int64
 3   Order Date              12079 non-null  datetime64[us]
 4   Rating                  12079 non-null  float64
 5   Number of Items         12079 non-null  int64
 6   Delivery Distance (km)  12079 non-null  float64
 7   Delivery Agent ID       12079 non-null  int64
 8   Order Status            12079 non-null  str
 9   Payment Method          12079 non-null  str
 10  Tip Amount (INR)        12079 non-null  int64
 11  Promo Code Applied      12079 non-null  str
 12  Has Free Delivery       12079 non-null  str
 13  res_id                  12079 non-null  int64
 14  name                    12079 non-null  str
 15  type                    11738 non-null  str
 16  address                 12074 non-null  str
 17  city                    12079 non-null  str
 18  locality                12079 non-null  str
 19  latitude                12079 non-null  float64
 20  longitude               12079 non-null  float64
 21  cuisines                12004 non-null  str
 22  timings                 11903 non-null  str
 23  average_cost_for_two    12079 non-null  int64
 24  price_range             12079 non-null  int64
 25  highlights              12079 non-null  str
 26  aggregate_rating        12079 non-null  float64
 27  votes                   12079 non-null  int64
 28  photo_count             12079 non-null  int64
 29  opentable_support       12071 non-null  float64
 30  delivery                12079 non-null  int64
 31  state                   12079 non-null  str
 32  area                    12079 non-null  int64
dtypes: datetime64[us](1), float64(6), int64(13), str(13)
memory usage: 3.0 MB

In [10]:
missing_values = df.isnull().sum()

missing_values[missing_values > 0].sort_values(ascending=False)

type                 341
timings              176
cuisines              75
opentable_support      8
address                5
dtype: int64

In [11]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 212

In [12]:
duplicate_rows = df[df.duplicated(keep=False)]

print("Total duplicate rows:", len(duplicate_rows))
duplicate_rows.head(10)

Total duplicate rows: 406

,Order ID,Order Amount (INR),Delivery Time (mins),Order Date,Rating,Number of Items,Delivery Distance (km),Delivery Agent ID,Order Status,Payment Method,...,average_cost_for_two,price_range,highlights,aggregate_rating,votes,photo_count,opentable_support,delivery,state,area
67,60,456,44,2023-05-24,4.2,8,10.545600,566,In-Transit,UPI,...,250,1,"['Dinner', 'Cash', 'Takeaway Available', 'Brea...",3.9,81,2,0.0,1,Madhya Pradesh,308245
68,60,456,44,2023-05-24,4.2,8,10.545600,566,In-Transit,UPI,...,250,1,"['Dinner', 'Cash', 'Takeaway Available', 'Brea...",3.9,81,2,0.0,1,Madhya Pradesh,308245
111,98,2843,48,2024-07-25,1.0,2,5.237770,167,Delivered,Cash,...,1000,3,"['Dinner', 'Delivery', 'Credit Card', 'Lunch',...",4.1,2818,972,0.0,0,Tamil Nadu,130058
113,98,2843,48,2024-07-25,1.0,2,5.237770,167,Delivered,Cash,...,1000,3,"['Dinner', 'Delivery', 'Credit Card', 'Lunch',...",4.1,2818,972,0.0,0,Tamil Nadu,130058
289,248,1326,41,2023-10-07,3.7,7,1.248155,818,Cancelled,Debit Card,...,400,2,"['Lunch', 'Takeaway Available', 'Debit Card', ...",4.5,263,47,0.0,1,Uttar Pradesh,240928
290,248,1326,41,2023-10-07,3.7,7,1.248155,818,Cancelled,Debit Card,...,400,2,"['Lunch', 'Takeaway Available', 'Debit Card', ...",4.5,263,47,0.0,1,Uttar Pradesh,240928
335,286,2336,60,2023-10-06,4.8,6,5.606795,218,Delivered,Debit Card,...,200,1,"['Lunch', 'Delivery', 'Dinner', 'Cash', 'Takea...",3.9,90,5,0.0,1,Gujarat,196024
336,286,2336,60,2023-10-06,4.8,6,5.606795,218,Delivered,Debit Card,...,200,1,"['Lunch', 'Delivery', 'Dinner', 'Cash', 'Takea...",3.9,90,5,0.0,1,Gujarat,196024
342,291,1559,76,2024-08-19,3.0,2,1.683415,683,Delivered,Credit Card,...,300,1,"['Cash', 'Takeaway Available', 'Credit Card', ...",4.0,144,84,0.0,1,Maharashtra,307713
343,291,1559,76,2024-08-19,3.0,2,1.683415,683,Delivered,Credit Card,...,300,1,"['Cash', 'Takeaway Available', 'Credit Card', ...",4.0,144,84,0.0,1,Maharashtra,307713

In [13]:
print("Unique Order IDs:", df["Order ID"].nunique())
print("Total rows:", len(df))

Unique Order IDs: 10000
Total rows: 12079

In [14]:
categorical_columns = [
    "Order Status",
    "Payment Method",
    "Promo Code Applied",
    "Has Free Delivery",
    "type",
    "city",
    "state"
]

for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False).head(20))

--- Order Status ---
Order Status
Delivered     4093
In-Transit    4089
Cancelled     3897
Name: count, dtype: int64

--- Payment Method ---
Payment Method
UPI            2473
Cash           2418
Net Banking    2405
Debit Card     2395
Credit Card    2388
Name: count, dtype: int64

--- Promo Code Applied ---
Promo Code Applied
Yes    6147
No     5932
Name: count, dtype: int64

--- Has Free Delivery ---
Has Free Delivery
No     6062
Yes    6017
Name: count, dtype: int64

--- type ---
type
Quick Bites        3225
Casual Dining      2837
Café                980
Dessert Parlour     734
Bakery              679
Sweet Shop          512
Beverage Shop       454
NaN                 341
Fine Dining         330
Food Court          322
Bar                 310
Dhaba               256
Kiosk               237
Lounge              192
Food Truck          153
Bhojanalya          137
Mess                 97
Paan Shop            85
Pub                  75
Confectionery        35
Name: count, dtype: int64

--- city ---
city
Chennai       826
Mumbai        741
Aurangabad    634
Bangalore     479
Pune          405
New Delhi     399
Lucknow       299
Jaipur        288
Ahmedabad     274
Kolkata       259
Kochi         256
Indore        244
Bhopal        212
Nagpur        208
Ludhiana      203
Surat         194
Vadodara      188
Agra          186
Coimbatore    186
Ajmer         174
Name: count, dtype: int64

--- state ---
state
Maharashtra          2156
Uttar Pradesh        1310
Tamil Nadu           1302
Gujarat               936
Rajasthan             884
Madhya Pradesh        714
Karnataka             710
Punjab                607
Bihar                 457
Delhi                 399
West Bengal           399
Kerala                368
Jharkhand             267
Uttarakhand           238
Andhra Pradesh        215
Haryana               202
Telangana             195
Chhattisgarh          169
Assam                 161
Jammu and Kashmir     141
Name: count, dtype: int64

In [15]:
numeric_columns = [
    "Order Amount (INR)",
    "Delivery Time (mins)",
    "Rating",
    "Number of Items",
    "Delivery Distance (km)",
    "Tip Amount (INR)"
]

df[numeric_columns].describe().T

,count,mean,std,min,25%,50%,75%,max
Order Amount (INR),12079.0,1579.123355,825.658629,150.000000,862.000000,1583.000000,2287.000000,2999.000000
Delivery Time (mins),12079.0,49.578359,23.196654,10.000000,29.000000,50.000000,70.000000,89.000000
Rating,12079.0,3.004330,1.160856,1.000000,2.000000,3.000000,4.000000,5.000000
Number of Items,12079.0,5.016392,2.593551,1.000000,3.000000,5.000000,7.000000,9.000000
Delivery Distance (km),12079.0,7.653219,4.207720,0.500953,3.922855,7.640077,11.261738,14.999011
Tip Amount (INR),12079.0,99.022104,57.890396,0.000000,49.000000,99.000000,149.000000,199.000000

In [16]:
checks = {
    "Negative Order Amount": (df["Order Amount (INR)"] < 0).sum(),
    "Zero Order Amount": (df["Order Amount (INR)"] == 0).sum(),
    "Negative Delivery Time": (df["Delivery Time (mins)"] < 0).sum(),
    "Zero Delivery Time": (df["Delivery Time (mins)"] == 0).sum(),
    "Invalid Rating": ((df["Rating"] < 0) | (df["Rating"] > 5)).sum(),
    "Zero Items": (df["Number of Items"] == 0).sum(),
    "Negative Distance": (df["Delivery Distance (km)"] < 0).sum(),
    "Negative Tip": (df["Tip Amount (INR)"] < 0).sum()
}

checks

{'Negative Order Amount': np.int64(0),
 'Zero Order Amount': np.int64(0),
 'Negative Delivery Time': np.int64(0),
 'Zero Delivery Time': np.int64(0),
 'Invalid Rating': np.int64(0),
 'Zero Items': np.int64(0),
 'Negative Distance': np.int64(0),
 'Negative Tip': np.int64(0)}

In [17]:
print("Minimum date:", df["Order Date"].min())
print("Maximum date:", df["Order Date"].max())

Minimum date: 2023-01-01 00:00:00
Maximum date: 2024-10-01 00:00:00

In [18]:
print(df["Order Date"].dt.year.value_counts().sort_index())

Order Date
2023    6844
2024    5235
Name: count, dtype: int64

In [19]:
order_id_counts = df["Order ID"].value_counts()

print("Orders appearing more than once:",
      (order_id_counts > 1).sum())

print("\nMaximum appearances of one Order ID:",
      order_id_counts.max())

order_id_counts[order_id_counts > 1].head(20)

Orders appearing more than once: 1822

Maximum appearances of one Order ID: 9

Order ID
525     9
2162    9
4626    9
8077    9
9250    9
3916    6
823     5
4740    5
5542    5
9926    5
259     4
383     4
546     4
994     4
1716    4
2017    4
2037    4
2062    4
2323    4
2458    4
Name: count, dtype: int64

In [20]:
repeated_ids = order_id_counts[order_id_counts > 1].index

repeated_orders = df[df["Order ID"].isin(repeated_ids)]

repeated_orders.sort_values("Order ID").head(20)

,Order ID,Order Amount (INR),Delivery Time (mins),Order Date,Rating,Number of Items,Delivery Distance (km),Delivery Agent ID,Order Status,Payment Method,...,average_cost_for_two,price_range,highlights,aggregate_rating,votes,photo_count,opentable_support,delivery,state,area
18,19,534,80,2023-05-05,1.2,3,2.932495,914,Cancelled,UPI,...,700,2,"['Dinner', 'Cash', 'Takeaway Available', 'Debi...",3.8,324,297,0.0,1,Tamil Nadu,130058
19,19,534,80,2023-05-05,1.2,3,2.932495,914,Cancelled,UPI,...,700,2,"['Dinner', 'Cash', 'Takeaway Available', 'Debi...",3.8,324,297,0.0,0,Tamil Nadu,130058
20,20,1085,57,2024-07-10,4.0,8,14.592409,476,Delivered,Cash,...,500,2,"['Lunch', 'Breakfast', 'Dinner', 'Indoor Seati...",3.4,12,5,0.0,0,Maharashtra,307713
21,20,1085,57,2024-07-10,4.0,8,14.592409,476,Delivered,Cash,...,500,2,"['Lunch', 'Breakfast', 'Dinner', 'Indoor Seati...",3.4,12,5,0.0,0,Bihar,94163
23,22,1165,41,2023-10-16,3.1,9,2.088826,813,In-Transit,Net Banking,...,300,1,"['Cash', 'Takeaway Available', 'No Seating Ava...",3.7,35,20,0.0,1,Maharashtra,307713
24,22,1165,41,2023-10-16,3.1,9,2.088826,813,In-Transit,Net Banking,...,300,1,"['Cash', 'Takeaway Available', 'No Seating Ava...",3.7,35,20,0.0,0,Maharashtra,307713
29,27,2516,61,2023-08-20,1.4,9,1.827588,565,In-Transit,UPI,...,600,2,"['Delivery', 'Cash', 'Lunch', 'Takeaway Availa...",4.0,282,6,0.0,1,Punjab,50362
30,27,2516,61,2023-08-20,1.4,9,1.827588,565,In-Transit,UPI,...,600,2,"['Delivery', 'Cash', 'Lunch', 'Takeaway Availa...",4.0,282,6,0.0,0,Punjab,50362
31,28,1256,43,2023-09-13,4.6,7,12.027227,537,In-Transit,Net Banking,...,300,1,"['Cash', 'Takeaway Available', 'Debit Card', '...",3.5,46,130,0.0,1,Maharashtra,307713
32,28,1256,43,2023-09-13,4.6,7,12.027227,537,In-Transit,Net Banking,...,300,1,"['Cash', 'Takeaway Available', 'Debit Card', '...",3.5,46,130,0.0,0,Maharashtra,307713
33,29,761,53,2024-04-08,3.7,7,12.093283,208,In-Transit,Credit Card,...,400,1,"['Credit Card', 'Delivery', 'Debit Card', 'Cas...",4.3,257,562,0.0,1,Maharashtra,307713
34,29,761,53,2024-04-08,3.7,7,12.093283,208,In-Transit,Credit Card,...,400,1,"['Credit Card', 'Delivery', 'Debit Card', 'Cas...",4.3,257,562,0.0,0,Maharashtra,307713
61,56,308,20,2024-08-14,3.2,6,2.738931,643,In-Transit,Credit Card,...,100,1,"['Dinner', 'Cash', 'Lunch', 'Takeaway Availabl...",0.0,2,0,0.0,0,Maharashtra,307713
62,56,308,20,2024-08-14,3.2,6,2.738931,643,In-Transit,Credit Card,...,100,1,"['Dinner', 'Cash', 'Lunch', 'Takeaway Availabl...",0.0,2,0,0.0,0,Bihar,94163
66,60,456,44,2023-05-24,4.2,8,10.545600,566,In-Transit,UPI,...,250,1,"['Dinner', 'Cash', 'Takeaway Available', 'Brea...",3.9,81,2,0.0,0,Madhya Pradesh,308245
67,60,456,44,2023-05-24,4.2,8,10.545600,566,In-Transit,UPI,...,250,1,"['Dinner', 'Cash', 'Takeaway Available', 'Brea...",3.9,81,2,0.0,1,Madhya Pradesh,308245
68,60,456,44,2023-05-24,4.2,8,10.545600,566,In-Transit,UPI,...,250,1,"['Dinner', 'Cash', 'Takeaway Available', 'Brea...",3.9,81,2,0.0,1,Madhya Pradesh,308245
73,65,2962,56,2024-01-16,1.8,4,6.812872,208,Delivered,Debit Card,...,1000,3,"['Delivery', 'Credit Card', 'Debit Card', 'Cas...",4.3,1531,1564,0.0,1,Maharashtra,307713
74,65,2962,56,2024-01-16,1.8,4,6.812872,208,Delivered,Debit Card,...,1000,3,"['Delivery', 'Credit Card', 'Debit Card', 'Cas...",4.3,1531,1564,0.0,0,Maharashtra,307713
81,72,1562,22,2023-04-25,2.7,3,1.641029,366,Delivered,Debit Card,...,800,3,"['Lunch', 'Delivery', 'Debit Card', 'No Alcoho...",3.9,249,114,0.0,1,Gujarat,196024

In [21]:
id_variation = (
    df.groupby("Order ID")
      .agg(
          rows=("Order ID", "size"),
          unique_status=("Order Status", "nunique"),
          unique_amount=("Order Amount (INR)", "nunique"),
          unique_restaurants=("res_id", "nunique"),
          unique_dates=("Order Date", "nunique")
      )
)

id_variation[id_variation["rows"] > 1].head(20)

          rows  unique_status  unique_amount  unique_restaurants  unique_dates
Order ID
19           2              1              1                   1             1
20           2              1              1                   1             1
22           2              1              1                   1             1
27           2              1              1                   1             1
28           2              1              1                   1             1
29           2              1              1                   1             1
56           2              1              1                   1             1
60           3              1              1                   1             1
65           2              1              1                   1             1
72           2              1              1                   1             1
80           2              1              1                   1             1
88           2              1              1                   1             1
91           2              1              1                   1             1
98           3              1              1                   1             1
99           2              1              1                   1             1
113          2              1              1                   1             1
115          3              1              1                   1             1
118          2              1              1                   1             1
132          2              1              1                   1             1
137          2              1              1                   1             1

In [22]:
# Check whether every repeated Order ID has identical records

duplicate_id_check = (
    df.groupby("Order ID")
      .nunique()
)

repeated_id_check = duplicate_id_check.loc[
    df["Order ID"].value_counts()
    .loc[lambda x: x > 1]
    .index
]

# Find repeated Order IDs where any column has different values
inconsistent_ids = repeated_id_check[
    (repeated_id_check > 1).any(axis=1)
]

print("Repeated Order IDs:", len(repeated_id_check))
print("Repeated IDs with different information:", len(inconsistent_ids))

inconsistent_ids

Repeated Order IDs: 1822
Repeated IDs with different information: 1707

,Order Amount (INR),Delivery Time (mins),Order Date,Rating,Number of Items,Delivery Distance (km),Delivery Agent ID,Order Status,Payment Method,Tip Amount (INR),...,average_cost_for_two,price_range,highlights,aggregate_rating,votes,photo_count,opentable_support,delivery,state,area
Order ID,,,,,,,,,,,,,,,,,,,,,
525,1,1,1,1,1,1,1,1,1,1,...,1,1,3,1,1,5,1,2,1,1
2162,1,1,1,1,1,1,1,1,1,1,...,1,1,3,1,1,5,1,2,1,1
4626,1,1,1,1,1,1,1,1,1,1,...,1,1,3,1,1,5,1,2,1,1
8077,1,1,1,1,1,1,1,1,1,1,...,1,1,3,1,1,5,1,2,1,1
9250,1,1,1,1,1,1,1,1,1,1,...,1,1,3,1,1,5,1,2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9967,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,2,1,1
9970,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,2
9982,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,2,1,1
9989,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,2
9999,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,2,2

In [23]:
df_clean = df.drop_duplicates().copy()

print("Original rows:", len(df))
print("Rows after removing exact duplicates:", len(df_clean))
print("Rows removed:", len(df) - len(df_clean))

Original rows: 12079
Rows after removing exact duplicates: 11867
Rows removed: 212

In [24]:
print("Remaining exact duplicates:", df_clean.duplicated().sum())

Remaining exact duplicates: 0

In [26]:
df[df["Order ID"] == 525].T

,623,624,625,626,627,628,629,630,631
Order ID,525,525,525,525,525,525,525,525,525
Order Amount (INR),2679,2679,2679,2679,2679,2679,2679,2679,2679
Delivery Time (mins),37,37,37,37,37,37,37,37,37
Order Date,2023-09-26 00:00:00,2023-09-26 00:00:00,2023-09-26 00:00:00,2023-09-26 00:00:00,2023-09-26 00:00:00,2023-09-26 00:00:00,2023-09-26 00:00:00,2023-09-26 00:00:00,2023-09-26 00:00:00
Rating,1.3,1.3,1.3,1.3,1.3,1.3,1.3,1.3,1.3
Number of Items,3,3,3,3,3,3,3,3,3
Delivery Distance (km),8.431244,8.431244,8.431244,8.431244,8.431244,8.431244,8.431244,8.431244,8.431244
Delivery Agent ID,252,252,252,252,252,252,252,252,252
Order Status,Cancelled,Cancelled,Cancelled,Cancelled,Cancelled,Cancelled,Cancelled,Cancelled,Cancelled
Payment Method,Debit Card,Debit Card,Debit Card,Debit Card,Debit Card,Debit Card,Debit Card,Debit Card,Debit Card
Tip Amount (INR),127,127,127,127,127,127,127,127,127
Promo Code Applied,No,No,No,No,No,No,No,No,No
Has Free Delivery,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes
res_id,18453954,18453954,18453954,18453954,18453954,18453954,18453954,18453954,18453954
name,Candy and Green,Candy and Green,Candy and Green,Candy and Green,Candy and Green,Candy and Green,Candy and Green,Candy and Green,Candy and Green
type,Casual Dining,Casual Dining,Casual Dining,Casual Dining,Casual Dining,Casual Dining,Casual Dining,Casual Dining,Casual Dining
address,"4th & 5th Floor, Hub Town Sky Bay, Bhulabhai D...","4th & 5th Floor, Hub Town Sky Bay, Bhulabhai D...","4th & 5th Floor, Hub Town Sky Bay, Bhulabhai D...","4th & 5th Floor, Hub Town Sky Bay, Bhulabhai D...","4th & 5th Floor, Hub Town Sky Bay, Bhulabhai D...","4th & 5th Floor, Hub Town Sky Bay, Bhulabhai D...","4th & 5th Floor, Hub Town Sky Bay, Bhulabhai D...","4th & 5th Floor, Hub Town Sky Bay, Bhulabhai D...","4th & 5th Floor, Hub Town Sky Bay, Bhulabhai D..."
city,Mumbai,Mumbai,Mumbai,Mumbai,Mumbai,Mumbai,Mumbai,Mumbai,Mumbai
locality,Breach Candy,Breach Candy,Breach Candy,Breach Candy,Breach Candy,Breach Candy,Breach Candy,Breach Candy,Breach Candy
latitude,18.9752,18.9752,18.9752,18.9752,18.9752,18.9752,18.9752,18.9752,18.9752
longitude,72.80624,72.80624,72.80624,72.80624,72.80624,72.80624,72.80624,72.80624,72.80624
cuisines,"Asian, Italian, Continental, Desserts, Healthy...","Asian, Italian, Continental, Desserts, Healthy...","Asian, Italian, Continental, Desserts, Healthy...","Asian, Italian, Continental, Desserts, Healthy...","Asian, Italian, Continental, Desserts, Healthy...","Asian, Italian, Continental, Desserts, Healthy...","Asian, Italian, Continental, Desserts, Healthy...","Asian, Italian, Continental, Desserts, Healthy...","Asian, Italian, Continental, Desserts, Healthy..."
timings,"12 Noon to 12 Midnight (Mon-Tue, Thu), 12 Noon...","12 Noon to 12 Midnight (Mon-Tue, Thu), 12 Noon...","12 Noon to 12 Midnight (Mon-Tue, Thu), 12 Noon...","12 Noon to 12 Midnight (Mon-Tue, Thu), 12 Noon...","12 Noon to 12 Midnight (Mon-Tue, Thu), 12 Noon...","12 Noon to 12 Midnight (Mon-Tue, Thu), 12 Noon...","12 Noon to 12 Midnight (Mon-Tue, Thu), 12 Noon...","12 Noon to 12 Midnight (Mon-Tue, Thu), 12 Noon...","12 Noon to 12 Midnight (Mon-Tue, Thu), 12 Noon..."
average_cost_for_two,1600,1600,1600,1600,1600,1600,1600,1600,1600
price_range,3,3,3,3,3,3,3,3,3
highlights,"['Credit Card', 'Debit Card', 'Dinner', 'Cash'...","['Credit Card', 'Debit Card', 'Dinner', 'Cash'...","['Credit Card', 'Debit Card', 'Dinner', 'Cash'...","['Credit Card', 'Debit Card', 'Dinner', 'Cash'...","['Cash', 'Credit Card', 'Debit Card', 'Dinner'...","['Dinner', 'Cash', 'Credit Card', 'Debit Card'...","['Dinner', 'Cash', 'Credit Card', 'Debit Card'...","['Dinner', 'Cash', 'Credit Card', 'Debit Card'...","['Dinner', 'Cash', 'Credit Card', 'Debit Card'..."
aggregate_rating,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5
votes,1168,1168,1168,1168,1168,1168,1168,1168,1168
photo_count,1744,1793,1801,1804,1804,1804,1804,1804,1797
opentable_support,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
delivery,1,1,1,1,1,0,1,1,1
state,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra,Maharashtra
area,307713,307713,307713,307713,307713,307713,307713,307713,307713

In [27]:
df[df["Order ID"] == 525][
    [
        "Order ID",
        "Order Amount (INR)",
        "Delivery Time (mins)",
        "Order Date",
        "Rating",
        "Number of Items",
        "Delivery Distance (km)",
        "Delivery Agent ID",
        "Order Status",
        "Payment Method",
        "res_id",
        "name",
        "city",
        "state"
    ]
]

,Order ID,Order Amount (INR),Delivery Time (mins),Order Date,Rating,Number of Items,Delivery Distance (km),Delivery Agent ID,Order Status,Payment Method,res_id,name,city,state
623,525,2679,37,2023-09-26,1.3,3,8.431244,252,Cancelled,Debit Card,18453954,Candy and Green,Mumbai,Maharashtra
624,525,2679,37,2023-09-26,1.3,3,8.431244,252,Cancelled,Debit Card,18453954,Candy and Green,Mumbai,Maharashtra
625,525,2679,37,2023-09-26,1.3,3,8.431244,252,Cancelled,Debit Card,18453954,Candy and Green,Mumbai,Maharashtra
626,525,2679,37,2023-09-26,1.3,3,8.431244,252,Cancelled,Debit Card,18453954,Candy and Green,Mumbai,Maharashtra
627,525,2679,37,2023-09-26,1.3,3,8.431244,252,Cancelled,Debit Card,18453954,Candy and Green,Mumbai,Maharashtra
628,525,2679,37,2023-09-26,1.3,3,8.431244,252,Cancelled,Debit Card,18453954,Candy and Green,Mumbai,Maharashtra
629,525,2679,37,2023-09-26,1.3,3,8.431244,252,Cancelled,Debit Card,18453954,Candy and Green,Mumbai,Maharashtra
630,525,2679,37,2023-09-26,1.3,3,8.431244,252,Cancelled,Debit Card,18453954,Candy and Green,Mumbai,Maharashtra
631,525,2679,37,2023-09-26,1.3,3,8.431244,252,Cancelled,Debit Card,18453954,Candy and Green,Mumbai,Maharashtra

In [28]:
df_clean = df.drop_duplicates().copy()

print("Original rows:", len(df))
print("Cleaned rows:", len(df_clean))
print("Removed rows:", len(df) - len(df_clean))

Original rows: 12079
Cleaned rows: 11867
Removed rows: 212

In [29]:
print("Remaining duplicates:", df_clean.duplicated().sum())

Remaining duplicates: 0

In [30]:
df_clean["type"] = df_clean["type"].fillna("Unknown")

df_clean["cuisines"] = df_clean["cuisines"].fillna("Unknown")

df_clean["timings"] = df_clean["timings"].fillna("Not Available")

df_clean["address"] = df_clean["address"].fillna("Address Not Available")

df_clean["opentable_support"] = df_clean["opentable_support"].fillna(0)

In [31]:
df_clean.isnull().sum()[df_clean.isnull().sum() > 0]

Series([], dtype: int64)

In [32]:
df_clean["Month"] = df_clean["Order Date"].dt.month_name()

In [33]:
df_clean["Year"] = df_clean["Order Date"].dt.year

In [34]:
df_clean["Day"] = df_clean["Order Date"].dt.day_name()

In [35]:
df_clean["Quarter"] = df_clean["Order Date"].dt.quarter

In [36]:
df_clean["Is_Delivered"] = (
    df_clean["Order Status"] == "Delivered"
).astype(int)

In [37]:
df_clean["Is_Cancelled"] = (
    df_clean["Order Status"] == "Cancelled"
).astype(int)

In [38]:
df_clean["Has_Promo"] = (
    df_clean["Promo Code Applied"] == "Yes"
).astype(int)

In [39]:
df_clean["Free_Delivery"] = (
    df_clean["Has Free Delivery"] == "Yes"
).astype(int)

In [40]:
df_clean["Completed_Revenue"] = np.where(
    df_clean["Order Status"] == "Delivered",
    df_clean["Order Amount (INR)"],
    0
)

In [41]:
df_clean.to_csv(
    "../data/cleaned/food_delivery_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!